### ISSUE TITLE
createReducer functions seems wrong

### ISSUE THREAD

**Issue by Haotian-InfoTrack** [wwayne/react-native-nba-app#11] opened 2016-01-10 01:13 UTC
When I used the createReducer function which implemented in utils/createReducer.js, I got the following error:

`One of the sources to assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.`

`Unhandled JS Exception: One of the sources to assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.`

After I swap to the one which listed in Redux documentation, error gone:

``` js
export default function createReducer(initialState, handlers) {
  return function reducer(state = initialState, action) {
    if (handlers.hasOwnProperty(action.type)) {
      return handlers[action.type](state, action)
    } else {
      return state
    }
  }
}
```

**Comment by wwayne** [comment] 2016-01-10 01:44
I doubt it is caused by node version, which version you are using? I haven't met with such error and I'm using v5.1.1.
The `action.type` in my code is `Symbol` type, I don't know if it has something to do with it.

**Comment by Haotian-InfoTrack** [comment] 2016-01-10 02:08
my node version is v4.2.2

**Comment by wwayne** [comment] 2016-01-18 09:33
I still don't know why this error happen, but this is an edge case and you have solved it, could be some version problem, let's close this ticket

**Closed as completed by wwayne** 2016-01-18 09:33 UTC
